# Generated by Django 5.2.8 on 2025-11-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_foto_default_perfil_avatar_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo',
        ),
    ]
